//const add = require('./utils.js')
//const sum = add(4,-2)
//console.log(sum)
const validator = require('validator')
const getNotes = require('./notes.js')
const s1=getNotes()
console.log(s1)
console.log(validator.isEmail('dhiraksit@gmail.com'))
console.log(validator.isURL('https/www.youtube.com'))